Setup called........
8delete_account called............
Timeout Exception for alert: when credentials are right alert will not pop up ignore exception message  TimeoutException
Login is successful
Login validation is successful with mngr287834
Total Row: 81
Last Cust Id : 60573
Exception from Closing popup: TimeoutException
Error in Common_Package.BankApp_CommonFunctons on line 131  TimeoutException Message: 

Clicked successfully on:  new account
Added Account successfully

Writing cust_id and acc_id Information : 
cust_id file Name :  LastAdded_AccountID_CustID.txt
cust_id file Absolute Path :  E:\Vidyashri\PythonSeleniumProjects\Guru99BankProj\Common_Package\LastAdded_AccountID_CustID.txt
Writing to cust_id,acc_id into File
Stephen Lewis is matching Of id 60573 from Customer_ID
markwallace@gmail.com is matching of id 60573 from Customer_ID
Initial amount added 3000
Validation is done for added account 84449 of type Savings Successfully!!!
Total row in excel after adding new account: 82
Account Id to delete is : 84449
Acc id to delete: 84449
Clicked successfully on Menu :  Delete Account
Do you really want to delete this Account?
Account Deleted Sucessfully
Row 82,Col B:
Total Row : 82
84449 got deleted from xls
Bank app logout
teardown called........
